### ISSUE TITLE
is MOD  compatible with forum version  3.0.11?

### ISSUE THREAD

**Issue by 7rack** [EXreaction/Anti-Spam-ACP#6]
i tried to intall Anti-Spam-ACP 1.0.5-dev by automod 1.0.2,but i get a warning"The target phpBB version for this MOD is 3.0.10, but your forum version is 3.0.11. Even if the install is successful the MOD might not work as expected and/or might break your forum. Please verify with the MOD author that this MOD is compatible with your forum version."
thank you for your works,if it is possible i wanna do localized support .

**Comment by EXreaction** [comment]
Yes, it is compatible with 3.0.11.
