### ISSUE TITLE
Add changelog to github

### ISSUE THREAD

**Issue by rakekniven** [EXreaction/Anti-Spam-ACP#7]
Hello,
could not find changelog at github or http://nmguse.webfactional.com/forum/viewtopic.php?f=31&t=941

Thx.

btw. what are the changes from 1.0.5 compared to 1.0.6?

**Comment by EXreaction** [comment]
Change log: https://github.com/EXreaction/Anti-Spam-ACP/blob/master/install.xml

Update instructions: https://github.com/EXreaction/Anti-Spam-ACP/blob/master/contrib/update/1.0.5%20to%201.0.6.xml
